wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: Transformer
dataset:
  desc: null
  value: wikitext
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690569334.050362
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.2
      5: 0.15.7
      6: 4.31.0
      8:
      - 1
      - 3
      - 5
